package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.42

import (
	"context"
	"main/graph/model"
)

// Dog is the resolver for the dog field.
func (r *queryResolver) Dog(ctx context.Context) (*model.Dog, error) {
	return dog("4321", "Spot"), nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
